### ISSUE TITLE
 Cannot read property 'url' of null     

### ISSUE THREAD

**Issue by easyrun32** [swina/nuxpresso-nuxt#1]
Hey awesome repository!

I'm getting this error 
```
Cannot read property 'url' of null                                                                                 18:55:17

  at nuxt.config.js:91:15
  at v (node_modules/jiti/dist/jiti.js:1:54801)
  at Object.loadNuxtConfig (node_modules/@nuxt/config/dist/config.js:1082:15)
  at loadNuxtConfig (node_modules/@nuxt/cli/dist/cli-index.js:338:32)
  at NuxtCommand.getNuxtConfig (node_modules/@nuxt/cli/dist/cli-index.js:463:26)
  at Object._listenDev (node_modules/@nuxt/cli/dist/cli-dev.js:75:30)
  at Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:58:25)
  at Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:52:16)
  at NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:22)

```

Here's my .env

API_URL=http://localhost:1337/

FULL_STATIC=true
LOCAL_ASSETS=true
UPLOADS_FOLDER=/nuxpresso/nuxpresso-strapi/public/uploads
GOOGLE_ANALYTICS=UA-XXXX
RECAPTCHA=__API_KEY__
FONT_FAMILIES=Barlow+Condensed
NUXPRESSO_TITLE=nuxpresso
NUXPRESSO_HEADLINE=Your next CMS
SITE_EMAIL=__email__
FORM_SENDER=__form_sender_endpoint

I was also curious on how the whole multi site thing worked!

Thanks!

**Comment by swina** [comment]
Hi I will check it out ti reproduce your error. Btw I created a new version based on the same principles as nuxpresso and you can find here

https://whoobe.vercel.app

Repo

https://github.com/swina/whoobejs

For an online demo of the editor

https://whoobe-studio-demo.vercel.app

It's on a heroku dyno so authentication can require some seconds in order to start the dyno istance.

It's open source project and you can contribute as well.
I can also setup a live demo how to use whoobe to manage different projects, generate them and deploy.
